[mysqld]
basedir=C:\Program Files\MySQL\MySQL Server 8.4
datadir=D:\Java agent\.local\mysql\data
port=3306
bind-address=127.0.0.1
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
[client]
port=3306
default-character-set=utf8mb4